### ISSUE TITLE
WebP Server throws main.imageExists Error

### ISSUE THREAD

**Issue by dantio** [webp-sh/webp_server_go#117]
**Describe the bug**
Docker WebP Server throws "main.imageExists" and restarts. 
It seems like it happens when a image is beeing is accessed concurrently.

**To Reproduce**
2 WebP Server on different Nodes.
Shared "exhaust" folder between nodes (glusterfs).

**Expected behavior**
Normal behavior.

**Screenshots and logs**
```
webp_1_257cddb385a8 | panic: runtime error: invalid memory address or nil pointer dereference
webp_1_257cddb385a8 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x74eb37]
webp_1_257cddb385a8 |
webp_1_257cddb385a8 | goroutine 54 [running]:
webp_1_257cddb385a8 | main.imageExists({0xc0003b6b90, 0x4f})
webp_1_257cddb385a8 |   /build/helper.go:64 +0xb7
webp_1_257cddb385a8 | main.convertFilter({0xc0003b6a50, 0x41}, {0xc0003b6b90, 0x4f}, {0xc0003b6b40, 0x4f}, 0x0)
webp_1_257cddb385a8 |   /build/encoder.go:26 +0x46
webp_1_257cddb385a8 | main.convert(0xc0003d8000)
webp_1_257cddb385a8 |   /build/router.go:68 +0x2a5
webp_1_257cddb385a8 | github.com/gofiber/fiber/v2.(*App).next(0xc0001c4c60, 0xc0003d8000)
webp_1_257cddb385a8 |   /go/pkg/mod/github.com/webp-sh/fiber/v2@v2.4.0/router.go:126 +0x1d8
webp_1_257cddb385a8 | github.com/gofiber/fiber/v2.(*Ctx).Next(0x30)
webp_1_257cddb385a8 |   /go/pkg/mod/github.com/webp-sh/fiber/v2@v2.4.0/ctx.go:637 +0x53
webp_1_257cddb385a8 | github.com/gofiber/fiber/v2/middleware/logger.New.func2(0xc0003d8000)
webp_1_257cddb385a8 |   /go/pkg/mod/github.com/webp-sh/fiber/v2@v2.4.0/middleware/logger/logger.go:154 +0x22b
webp_1_257cddb385a8 | github.com/gofiber/fiber/v2.(*App).next(0xc0001c4c60, 0xc0003d8000)
webp_1_257cddb385a8 |   /go/pkg/mod/github.com/webp-sh/fiber/v2@v2.4.0/router.go:126 +0x1d8
webp_1_257cddb385a8 | github.com/gofiber/fiber/v2.(*App).handler(0xc0001c4c60, 0x4b2377)
webp_1_257cddb385a8 |   /go/pkg/mod/github.com/webp-sh/fiber/v2@v2.4.0/router.go:154 +0xe5
webp_1_257cddb385a8 | github.com/valyala/fasthttp.(*Server).serveConn(0xc00016ab40, {0x8d95f0, 0xc0003960d0})
webp_1_257cddb385a8 |   /go/pkg/mod/github.com/valyala/fasthttp@v1.35.0/server.go:2338 +0x11ae
webp_1_257cddb385a8 | github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0001b92c0, 0xc0003aa040)
webp_1_257cddb385a8 |   /go/pkg/mod/github.com/valyala/fasthttp@v1.35.0/workerpool.go:224 +0xa9
webp_1_257cddb385a8 | github.com/valyala/fasthttp.(*workerPool).getCh.func1()
webp_1_257cddb385a8 |   /go/pkg/mod/github.com/valyala/fasthttp@v1.35.0/workerpool.go:196 +0x38
webp_1_257cddb385a8 | created by github.com/valyala/fasthttp.(*workerPool).getCh
webp_1_257cddb385a8 |   /go/pkg/mod/github.com/valyala/fasthttp@v1.35.0/workerpool.go:195 +0x1b5
```

**Environment (please complete the following information):**
 - OS: Debian 10, Docker
 -  Webp Server Go - v0.4.4

**Comment by n0vad3v** [comment]
Thanks for reporting this, we will dig into this problem further.

But for now we recommend you not to share the exhaust path.

**Comment by dantio** [comment]
I have disabled the second WebP server and it tuns out it was still throwing the error. I'll try to add debug to imageExists function.

**Comment by dantio** [comment]
I have changed in helper.go:
```
func imageExists(filename string) bool {
	info, err := os.Stat(filename)
	if os.IsNotExist(err) {
		return false
	}

	if err != nil {
		log.Error(err)
		return true
	}

	log.Debugf("file %s exists!", filename)
	return !info.IsDir()
}
```

I have the errors like:
`level=error msg="stat userfiles/7715851/image/Notification-light-w360h205.jpg.1650530541.webp: input/output error" func="[65:main.imageExists()]"`

How can I get more information about what caused the error?

**Comment by dantio** [comment]
I have found out that I also can't cd to the named folder. It's probably not WebP server related and I have a hardware issue..

**Comment by n0vad3v** [comment]
Emm, might this possible hardware issue also caused issue https://github.com/webp-sh/webp_server_go/issues/116?

**Comment by dantio** [comment]
Error is not related to webp Server. Thank you.
